"""A small reference specimen showing Python types, aliases, and callable APIs.

Generated by Python Autodoc. Types link to local definitions; signatures retain
annotations and defaults without importing this module.
"""
from typing import Callable, NamedTuple

class Vector3(NamedTuple):
    """A position in three-dimensional space."""
    x: float
    """Horizontal coordinate, in meters."""
    y: float
    """Vertical coordinate, in meters."""
    z: float = 0.0
    """Depth coordinate, in meters."""

EventHandler = Callable[[Vector3], None]
"""A callback receiving a position update."""

class Scene:
    """A named scene with typed spatial coordinates.

    Args:
        name: Display name for the scene.
        origin: Initial position, or None for the default origin.
    """
    visible: bool = True
    """Whether the scene is visible."""

    def __init__(self, name: str, *, origin: Vector3 | None = None):
        self.name = name
        self._origin = origin or Vector3(0, 0)

    @property
    def origin(self) -> Vector3:
        """The current position of the scene."""
        return self._origin

    def move(self, position: Vector3, /, *, relative: bool = False) -> Vector3:
        """Move the scene and return its new origin.

        :param position: Target position in meters.
        :param relative: Interpret the position relative to the current origin.
        :return: The resulting scene origin.
        """
        return position

    async def subscribe(self, handler: EventHandler, *, timeout: float = 30.0) -> None:
        """Receive position updates asynchronously.

        Args:
            handler: Callback invoked for each update.
            timeout: Maximum wait in seconds.
        Raises:
            TimeoutError: No update arrived before the timeout.
        """
        pass
